# Generated by Django 5.0 on 2023-12-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petconnect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='biografia',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='image',
            field=models.ImageField(blank=True, default='usuario_image/default.png', null=True, upload_to='usuario_image'),
        ),
    ]
