# Generated by Django 5.0 on 2023-12-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petconnect', '0002_usuario_biografia_usuario_cpf_alter_usuario_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='endereco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
