# Generated by Django 5.0 on 2023-12-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petconnect', '0004_rename_id_dono_animais_dono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animais',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='animais_image'),
        ),
    ]
