# Generated by Django 5.0 on 2023-12-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petconnect', '0005_alter_animais_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='animais',
            name='especie',
            field=models.CharField(default='Desconhecido', max_length=100),
        ),
        migrations.AddField(
            model_name='animais',
            name='sexo',
            field=models.CharField(default='Desconhecido', max_length=100),
        ),
    ]
