# Generated by Django 5.0 on 2024-01-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petconnect', '0006_animais_especie_animais_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data_hora_agendamento',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_hora_consulta',
            field=models.DateTimeField(),
        ),
    ]
