# Generated by Django 5.0 on 2024-01-25 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petconnect', '0008_remove_servico_id_promocao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='id_animal',
            new_name='animal',
        ),
        migrations.RenameField(
            model_name='agendamento',
            old_name='data_hora_agendamento',
            new_name='data_agendamento',
        ),
        migrations.RenameField(
            model_name='agendamento',
            old_name='data_hora_consulta',
            new_name='data_consulta',
        ),
        migrations.RenameField(
            model_name='agendamento',
            old_name='desc_problema',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='agendamento',
            old_name='id_loja',
            new_name='loja',
        ),
        migrations.RenameField(
            model_name='agendamento',
            old_name='id_servico',
            new_name='servico',
        ),
        migrations.RenameField(
            model_name='agendamento',
            old_name='id_usuario',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='loja',
            old_name='available',
            new_name='disponvel',
        ),
        migrations.RenameField(
            model_name='loja',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='id_loja',
            new_name='loja',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='password',
        ),
    ]
