# Generated by Django 5.0 on 2024-01-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petconnect', '0010_remove_agendamento_loja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='descricao',
            field=models.TextField(max_length=500),
        ),
    ]
